// <auto-generated />
namespace Chef_Zilla.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeToReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeToReview));
        
        string IMigrationMetadata.Id
        {
            get { return "202009170959569_changeToReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
